# Generated by Django 4.0.2 on 2022-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dash_sum_snp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('state_ab', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=100)),
                ('county_ab', models.CharField(max_length=2)),
                ('fips', models.IntegerField()),
                ('county_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('tot_pop', models.IntegerField()),
                ('med_hh_inc', models.IntegerField()),
                ('estabs', models.IntegerField()),
                ('emp', models.IntegerField()),
                ('tot_hh_18', models.IntegerField()),
                ('tot_hh_no_int_18', models.IntegerField()),
                ('tot_hh_brdbnd_18', models.IntegerField()),
                ('unemployment_pct', models.FloatField()),
                ('in_st_hq', models.IntegerField()),
                ('branches', models.IntegerField()),
                ('depsumbr', models.IntegerField()),
            ],
        ),
    ]
