# Generated by Django 4.0.4 on 2022-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='neighbors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyname', models.CharField(max_length=100)),
                ('fips', models.IntegerField()),
                ('neighborname', models.CharField(max_length=100)),
                ('fipsneighbors', models.IntegerField()),
            ],
        ),
    ]
