# Generated by Django 4.0.2 on 2022-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dash_sum_ts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('state_ab', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=100)),
                ('county_ab', models.CharField(max_length=2)),
                ('fips', models.IntegerField()),
                ('county_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('sm_ln_amt', models.IntegerField()),
                ('med_ln_amt', models.IntegerField()),
                ('lg_ln_amt', models.IntegerField()),
                ('tot_pop', models.IntegerField()),
                ('med_hh_inc', models.IntegerField()),
                ('estabs', models.IntegerField()),
                ('estabs_entry', models.IntegerField()),
                ('estabs_exit', models.IntegerField()),
            ],
        ),
    ]
