# Generated by Django 4.0.4 on 2022-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_neighbors'),
    ]

    operations = [
        migrations.CreateModel(
            name='geoJson',
            fields=[
                ('type', models.CharField(max_length=7)),
                ('properties', models.CharField(max_length=200)),
                ('geometry', models.CharField(max_length=5000)),
                ('fips', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
